language: python
# Enable Travis container-based infrastructure
sudo: false
python:
  - "3.5"
  - "2.7"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
# Avoid "html5lib requires setuptools version 18.5" error
 - pip install --upgrade setuptools
 - pip install -r requirements.txt
 - python setup.py install # install nidmresults from sources
 - pip install ddt
script:
 - python test/test_reader.py
 